<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Promo Banners Base for Magento 2
 */ /** @var \Magento\Backend\Block\Template $block */?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<script>
    require([
        "jquery",
        "Amasty_PromoBanners/js/edit"
    ], function ($) {
        $(document).on('load', function () {
            var ampbForm = $('#edit_form');
            ampbForm.ampromobannerAddAttribute();

            $('[data-role=ampbanner_remove_attribute]').click(function () {
                ampbForm.ampromobannerAddAttribute('landingRemove', this);
                return false;
            });
        });

        window.showOptions = function (sel) {
            window.sel = sel;
            $.ajax({
                url: '<?= $escaper->escapeUrl($block->getUrl('ampromobanners/banners/options')); ?>',
                data: {code: sel.value},
                type: 'get',
                dataType: 'html',
                showLoader: true,
                context: $('#edit_form')
            }).done(function (data) {
                var valueElement = $(sel.parentElement.parentElement.parentElement.next())[0].children[1].children[0];
                if (!valueElement) {
                    valueElement = $(sel.parentElement.parentElement.next())[0].children[1].children[0];
                }
                $(valueElement).replaceWith(data);
            });
        }
    })
</script>
