<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Promo Banners Base for Magento 2
 */
/** @var \Amasty\PromoBanners\Block\Banner\Loader $block */
/** @var \Amasty\PromoBanners\ViewModel\BannersDataProvider $dataProvider */
$dataProvider = $block->getData('ampromoBannersDataProvider');

$data = [
    'bannersData' => $dataProvider->getBanners(),
    'requestUrl' => $block->getUrl('amasty_banners/data/getBannersData'),
    'categoryId' => $block->getCurrentCategoryId(),
    'productId' => $block->getCurrentProductId()
];
?>

<script type="text/x-magento-init">
    <?= /* @noEscape */ $dataProvider->serialize(['*' => ['Amasty_PromoBanners/js/loader' => $data]]) ?>
</script>
