<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/**
 * @var $block Logo
 */

use Tigren\PushNotifications\Block\Adminhtml\System\Config\Logo;

?>
<div class="tglogo-container">
    <span class="tgclose"></span>
    <span class="tglogo"
          data-role="tigren-notifications-logo-text"
            <?php if ($block->getValue()): ?> style="display: none" <?php endif; ?>>
            <?php echo $block->getLogoText(); ?>
        </span>

    <img id="tgimage_logo"
         class="image-logo"
        <?php if (!$block->getImageUrl()): ?> style="display: none" <?php endif; ?>
         src="<?php echo $block->getImageUrl(); ?>"
    />
    <label class="custom-file-input" for="<?php echo $block->getHtmlId(); ?>">
    </label>
    <input id="<?php echo $block->getHtmlId(); ?>"
           class="tgchoose-file input-file"
           type="<?php echo $block->getInputType(); ?>"
           name="<?php echo $block->getNamePrefix(); ?>"
           value="<?php echo $block->getImageUrl(); ?>"
    />
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#tgimage_logo').show().attr('src', e.target.result);
                };

                $('.tglogo').hide();

                reader.readAsDataURL(input.files[0]);
            }
        }

        var fileInputId = '<?php echo $block->getHtmlId(); ?>';

        $('#' + fileInputId).change(function () {
            readURL(this);
        });

        $('.tgclose').click(function () {
            $('#tgimage_logo').attr('src', '');
            $('.tglogo').show();
            $('.tgdelete-image').val(1);
        });
    });
</script>
