<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Base for Magento 2
 */
/**
 * @var \Amasty\Xsearch\Block\Adminhtml\RelatedTerms $block
 * @var \Amasty\Xsearch\Block\Adminhtml\RelatedTerms\Grid $blockGrid
 * @var \Magento\Framework\Escaper $escaper
 */

$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<fieldset class="fieldset admin__fieldset " id="grid_fieldset">
    <legend class="admin__legend legend">
        <span><?=  /* @noEscape */ __('Related Terms') ?></span>
    </legend>
    <br>

    <?= $block->getGridHtml() ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Amasty_Xsearch/js/search/term/assign-related": {
                    "selectedTerms": <?=  /* @noEscape */ $block->getTermsJson() ?>,
                    "gridJsObjectName": "<?= $escaper->escapeHtml($gridJsObjectName) ?>"
                }
            }
        }
    </script>
</fieldset>
