<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Base for Magento 2
 */
/**
 * @var Template $block
 * @var FormMiniData $viewModel
 * @var Escaper $escaper
 */

use Amasty\Xsearch\ViewModel\FormMiniData;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$viewModel = $block->getViewModel();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "amsearchAnalyticsCollector": {
                "minChars": <?= $escaper->escapeHtml($viewModel->getMinChars()) ?>
            }
        }
    }
</script>
<?php if ($viewModel->isFullScreenEnabled()): ?>
    <script type="text/x-magento-init">
        {
            ".page-header": {
                "amsearchFullWidth": {}
            }
        }
    </script>
<?php endif; ?>
